import { ExportExtractResponse, ExportProduct } from "types/pages/form-field";

export const mockFormExport: ExportExtractResponse = {
    "customs_procedure_type": 0,
    "item_code_option": false,
    "general_info": {
        export_type_code: '',
        customs_agency_code: '',
        declaration_processing_department_code: '',
        limited_import: '',
        transport_mode_code: '',
        expected_declaration_date: '',
        exporter_tax_code: '',
        exporter_name: '',
        exporter_postal_code: '',
        exporter_address: '',
        exporter_phone: '',
        export_consignor_tax_code: '',
        export_consignor_name: '',
        importer_tax_code: '',
        importer_name: '',
        importer_postal_code: '',
        importer_address_1: '',
        importer_address_2: '',
        importer_address_3: '',
        importer_address_4: '',
        import_country_code: '',
        customs_declarant_code: '',
        bill_of_lading_number: '',
        package_quantity: 0,
        package_quantity_unit: '',
        total_gross_weight: 0,
        gross_weight_unit: '',
        expected_warehouse_location_code: '',
        final_delivery_location: '',
        final_delivery_location_name: undefined,
        loading_location_code: '',
        loading_location_code_name: undefined,
        transport_vehicle_code: '',
        transport_vehicle_name: '',
        expected_departure_date: new Date().toISOString().split('T')[0],
        package_symbol_and_number: '',
        contract_number: '',
        contract_date: '',
        contract_expiration_date: '',
        export_license_code_1: '',
        export_license_number_1: '',
        export_license_code_2: '',
        export_license_number_2: '',
        export_license_code_3: '',
        export_license_number_3: '',
        export_license_code_4: '',
        export_license_number_4: '',
        export_license_code_5: '',
        export_license_number_5: '',
        invoice_type: '',
        electronic_invoice_receipt_number: '',
        invoice_number: '',
        invoice_issue_date: '',
        payment_method: '',
        invoice_price_type: '',
        invoice_condition: '',
        total_invoice_value: 0,
        invoice_currency_code: '',
        taxable_value: 0,
        taxable_value_currency_code: '',
        no_vnd_conversion: '',
        total_tax_value_allocation_coefficient: '',
        tax_payer: '',
        tax_payment_bank_code: '',
        credit_limit_issue_year: '',
        credit_limit_document_symbol: '',
        credit_limit_document_number: '',
        tax_payment_deadline_code: '',
        guarantee_bank_code: '',
        guarantee_issue_year: '',
        guarantee_document_symbol: '',
        guarantee_document_number: '',
        attachment_type_1: '',
        attachment_number_1: '',
        attachment_type_2: '',
        attachment_number_2: '',
        attachment_type_3: '',
        attachment_number_3: '',
        transport_departure_date: new Date().toISOString().split('T')[0],
        transit_location_code_1: '',
        transit_arrival_date_1: '',
        transit_departure_date_1: '',
        transit_location_code_2: '',
        transit_arrival_date_2: '',
        transit_departure_date_2: '',
        transit_location_code_3: '',
        transit_arrival_date_3: '',
        transit_departure_date_3: '',
        tax_transport_destination_code: '',
        tax_transport_destination_arrival_date: new Date().toISOString().split('T')[0],
        notes: '',
        internal_management_number: ''
    },
    "container_info": {
        loading_location_code_1: '',
        loading_location_code_2: '',
        loading_location_code_3: '',
        loading_location_code_4: '',
        loading_location_code_5: '',
        loading_location_name: '',
        address: '',

        container_number_1: '',
        container_number_2: '',
        container_number_3: '',
        container_number_4: '',
        container_number_5: '',
        container_number_6: '',
        container_number_7: '',
        container_number_8: '',
        container_number_9: '',
        container_number_10: '',
        container_number_11: '',
        container_number_12: '',
        container_number_13: '',
        container_number_14: '',
        container_number_15: '',
        container_number_16: '',
        container_number_17: '',
        container_number_18: '',
        container_number_19: '',
        container_number_20: '',
        container_number_21: '',
        container_number_22: '',
        container_number_23: '',
        container_number_24: '',
        container_number_25: '',
        container_number_26: '',
        container_number_27: '',
        container_number_28: '',
        container_number_29: '',
        container_number_30: '',
        container_number_31: '',
        container_number_32: '',
        container_number_33: '',
        container_number_34: '',
        container_number_35: '',
        container_number_36: '',
        container_number_37: '',
        container_number_38: '',
        container_number_39: '',
        container_number_40: '',
        container_number_41: '',
        container_number_42: '',
        container_number_43: '',
        container_number_44: '',
        container_number_45: '',
        container_number_46: '',
        container_number_47: '',
        container_number_48: '',
        container_number_49: '',
        container_number_50: '',
    },
}
export const mockFormExportProduct: ExportProduct = {
    item_code: "",
    item_name: "",
    hs_code: "",
    quantity: null,
    country_of_origin_code: "",
    quantity_unit: "",
    secondary_quantity: null,
    secondary_quantity_unit: "",
    invoice_unit_price: null,
    unit_price_currency_code: "",
    invoice_unit_price_unit: "",
    invoice_value: null,
    taxable_value: null,
    taxable_value_currency_code: "",
    export_import_ratio: null,
    absolute_tax_rate: null,
    absolute_tax_rate_unit: "",
    absolute_tax_currency_code: "",
    export_import_tax_amount: null,
    export_tax_exemption_reduction_code: "",
    export_tax_reduction_amount: null,
    item_sequence_on_temporary_import_export_declaration: null,
    export_tax_exemption_list_registration_number: "",
    corresponding_line_in_export_tax_exemption_list: null,
    legal_document_code_1: "",
    legal_document_code_2: "",
    legal_document_code_3: "",
    legal_document_code_4: "",
    legal_document_code_5: "",
    size_number: "",
    po_number: "",
    private_management_code: "",
}

export function initialExportFormFactory(initialFormValues: ExportExtractResponse |
    undefined, validationSchema: any, setInitialFormData: any) {
    return {
        initialValues: {
            //1
            customs_procedure_type: initialFormValues?.customs_procedure_type ?? 0,
            item_code_option: initialFormValues?.item_code_option ?? false,
            general_info: {
                export_type_code: initialFormValues?.general_info?.export_type_code ?? '',
                customs_agency_code: initialFormValues?.general_info?.customs_agency_code ?? '',
                declaration_processing_department_code: initialFormValues?.general_info?.declaration_processing_department_code ?? '',
                limited_import: initialFormValues?.general_info?.limited_import ?? '',
                transport_mode_code: initialFormValues?.general_info?.transport_mode_code ?? '',
                expected_declaration_date: initialFormValues?.general_info?.expected_declaration_date ?? '',
                exporter_tax_code: initialFormValues?.general_info?.exporter_tax_code ?? '',
                exporter_name: initialFormValues?.general_info?.exporter_name ?? '',
                exporter_postal_code: initialFormValues?.general_info?.exporter_postal_code ?? '',
                exporter_address: initialFormValues?.general_info?.exporter_address ?? '',
                exporter_phone: initialFormValues?.general_info?.exporter_phone ?? '',
                export_consignor_tax_code: initialFormValues?.general_info?.export_consignor_tax_code ?? '',
                export_consignor_name: initialFormValues?.general_info?.export_consignor_name ?? '',
                importer_tax_code: initialFormValues?.general_info?.importer_tax_code ?? '',
                importer_name: initialFormValues?.general_info?.importer_name ?? '',
                importer_postal_code: initialFormValues?.general_info?.importer_postal_code ?? '',
                importer_address_1: initialFormValues?.general_info?.importer_address_1 ?? '',
                importer_address_2: initialFormValues?.general_info?.importer_address_2 ?? '',
                importer_address_3: initialFormValues?.general_info?.importer_address_3 ?? '',
                importer_address_4: initialFormValues?.general_info?.importer_address_4 ?? '',
                import_country_code: initialFormValues?.general_info?.import_country_code ?? '',
                customs_declarant_code: initialFormValues?.general_info?.customs_declarant_code ?? '',
                bill_of_lading_number: initialFormValues?.general_info?.bill_of_lading_number ?? '',
                package_quantity: initialFormValues?.general_info?.package_quantity ?? '',
                package_quantity_unit: initialFormValues?.general_info?.package_quantity_unit ?? '',
                total_gross_weight: initialFormValues?.general_info?.total_gross_weight ?? '',
                gross_weight_unit: initialFormValues?.general_info?.gross_weight_unit ?? '',
                expected_warehouse_location_code: initialFormValues?.general_info?.expected_warehouse_location_code ?? '',
                final_delivery_location: initialFormValues?.general_info?.final_delivery_location ?? '',
                final_delivery_location_name: initialFormValues?.general_info?.final_delivery_location_name ?? undefined,
                loading_location_code: initialFormValues?.general_info?.loading_location_code ?? '',
                loading_location_code_name: initialFormValues?.general_info?.loading_location_code_name ?? undefined,
                transport_vehicle_code: initialFormValues?.general_info?.transport_vehicle_code ?? '',
                transport_vehicle_name: initialFormValues?.general_info?.transport_vehicle_name ?? '',
                expected_departure_date: new Date().toISOString().split('T')[0],
                package_symbol_and_number: initialFormValues?.general_info?.package_symbol_and_number ?? '',
                contract_number: initialFormValues?.general_info?.contract_number ?? '',
                contract_date: initialFormValues?.general_info?.contract_date ?? '',
                contract_expiration_date: initialFormValues?.general_info?.contract_expiration_date ?? '',
                export_license_code_1: initialFormValues?.general_info?.export_license_code_1 ?? '',
                export_license_number_1: initialFormValues?.general_info?.export_license_number_1 ?? '',
                export_license_code_2: initialFormValues?.general_info?.export_license_code_2 ?? '',
                export_license_number_2: initialFormValues?.general_info?.export_license_number_2 ?? '',
                export_license_code_3: initialFormValues?.general_info?.export_license_code_3 ?? '',
                export_license_number_3: initialFormValues?.general_info?.export_license_number_3 ?? '',
                export_license_code_4: initialFormValues?.general_info?.export_license_code_4 ?? '',
                export_license_number_4: initialFormValues?.general_info?.export_license_number_4 ?? '',
                export_license_code_5: initialFormValues?.general_info?.export_license_code_5 ?? '',
                export_license_number_5: initialFormValues?.general_info?.export_license_number_5 ?? '',
                invoice_type: initialFormValues?.general_info?.invoice_type ?? '',
                electronic_invoice_receipt_number: initialFormValues?.general_info?.electronic_invoice_receipt_number ?? '',
                invoice_number: initialFormValues?.general_info?.invoice_number ?? '',
                invoice_issue_date: initialFormValues?.general_info?.invoice_issue_date ?? '',
                payment_method: initialFormValues?.general_info?.payment_method ?? '',
                invoice_price_type: initialFormValues?.general_info?.invoice_price_type ?? '',
                invoice_condition: initialFormValues?.general_info?.invoice_condition ?? '',
                total_invoice_value: initialFormValues?.general_info?.total_invoice_value ?? '',
                invoice_currency_code: initialFormValues?.general_info?.invoice_currency_code ?? '',
                taxable_value: initialFormValues?.general_info?.taxable_value ?? '',
                taxable_value_currency_code: initialFormValues?.general_info?.taxable_value_currency_code ?? '',
                no_vnd_conversion: initialFormValues?.general_info?.no_vnd_conversion ?? '',
                total_tax_value_allocation_coefficient: initialFormValues?.general_info?.total_tax_value_allocation_coefficient ?? '',
                tax_payer: initialFormValues?.general_info?.tax_payer ?? '',
                tax_payment_bank_code: initialFormValues?.general_info?.tax_payment_bank_code ?? '',
                credit_limit_issue_year: initialFormValues?.general_info?.credit_limit_issue_year ?? '',
                credit_limit_document_symbol: initialFormValues?.general_info?.credit_limit_document_symbol ?? '',
                credit_limit_document_number: initialFormValues?.general_info?.credit_limit_document_number ?? '',
                tax_payment_deadline_code: initialFormValues?.general_info?.tax_payment_deadline_code ?? '',
                guarantee_bank_code: initialFormValues?.general_info?.guarantee_bank_code ?? '',
                guarantee_issue_year: initialFormValues?.general_info?.guarantee_issue_year ?? '',
                guarantee_document_symbol: initialFormValues?.general_info?.guarantee_document_symbol ?? '',
                guarantee_document_number: initialFormValues?.general_info?.guarantee_document_number ?? '',
                attachment_type_1: initialFormValues?.general_info?.attachment_type_1 ?? '',
                attachment_number_1: initialFormValues?.general_info?.attachment_number_1 ?? '',
                attachment_type_2: initialFormValues?.general_info?.attachment_type_2 ?? '',
                attachment_number_2: initialFormValues?.general_info?.attachment_number_2 ?? '',
                attachment_type_3: initialFormValues?.general_info?.attachment_type_3 ?? '',
                attachment_number_3: initialFormValues?.general_info?.attachment_number_3 ?? '',
                transport_departure_date: new Date().toISOString().split('T')[0],
                transit_location_code_1: initialFormValues?.general_info?.transit_location_code_1 ?? '',
                transit_arrival_date_1: initialFormValues?.general_info?.transit_arrival_date_1 ?? '',
                transit_departure_date_1: initialFormValues?.general_info?.transit_departure_date_1 ?? '',
                transit_location_code_2: initialFormValues?.general_info?.transit_location_code_2 ?? '',
                transit_arrival_date_2: initialFormValues?.general_info?.transit_arrival_date_2 ?? '',
                transit_departure_date_2: initialFormValues?.general_info?.transit_departure_date_2 ?? '',
                transit_location_code_3: initialFormValues?.general_info?.transit_location_code_3 ?? '',
                transit_arrival_date_3: initialFormValues?.general_info?.transit_arrival_date_3 ?? '',
                transit_departure_date_3: initialFormValues?.general_info?.transit_departure_date_3 ?? '',
                tax_transport_destination_code: initialFormValues?.general_info?.tax_transport_destination_code ?? '',
                tax_transport_destination_arrival_date: new Date().toISOString().split('T')[0],
                notes: initialFormValues?.general_info?.notes ?? '',
                internal_management_number: initialFormValues?.general_info?.internal_management_number ?? ''
            },
            container_info: {
                loading_location_code_1: initialFormValues?.container_info?.loading_location_code_1 ?? '',
                loading_location_code_2: initialFormValues?.container_info?.loading_location_code_2 ?? '',
                loading_location_code_3: initialFormValues?.container_info?.loading_location_code_3 ?? '',
                loading_location_code_4: initialFormValues?.container_info?.loading_location_code_4 ?? '',
                loading_location_code_5: initialFormValues?.container_info?.loading_location_code_5 ?? '',
                loading_location_name: initialFormValues?.container_info?.loading_location_name ?? '',
                address: initialFormValues?.container_info?.address ?? '',

                container_number_1: initialFormValues?.container_info?.container_number_1 ?? '',
                container_number_2: initialFormValues?.container_info?.container_number_2 ?? '',
                container_number_3: initialFormValues?.container_info?.container_number_3 ?? '',
                container_number_4: initialFormValues?.container_info?.container_number_4 ?? '',
                container_number_5: initialFormValues?.container_info?.container_number_5 ?? '',
                container_number_6: initialFormValues?.container_info?.container_number_6 ?? '',
                container_number_7: initialFormValues?.container_info?.container_number_7 ?? '',
                container_number_8: initialFormValues?.container_info?.container_number_8 ?? '',
                container_number_9: initialFormValues?.container_info?.container_number_9 ?? '',
                container_number_10: initialFormValues?.container_info?.container_number_10 ?? '',
                container_number_11: initialFormValues?.container_info?.container_number_11 ?? '',
                container_number_12: initialFormValues?.container_info?.container_number_12 ?? '',
                container_number_13: initialFormValues?.container_info?.container_number_13 ?? '',
                container_number_14: initialFormValues?.container_info?.container_number_14 ?? '',
                container_number_15: initialFormValues?.container_info?.container_number_15 ?? '',
                container_number_16: initialFormValues?.container_info?.container_number_16 ?? '',
                container_number_17: initialFormValues?.container_info?.container_number_17 ?? '',
                container_number_18: initialFormValues?.container_info?.container_number_18 ?? '',
                container_number_19: initialFormValues?.container_info?.container_number_19 ?? '',
                container_number_20: initialFormValues?.container_info?.container_number_20 ?? '',
                container_number_21: initialFormValues?.container_info?.container_number_21 ?? '',
                container_number_22: initialFormValues?.container_info?.container_number_22 ?? '',
                container_number_23: initialFormValues?.container_info?.container_number_23 ?? '',
                container_number_24: initialFormValues?.container_info?.container_number_24 ?? '',
                container_number_25: initialFormValues?.container_info?.container_number_25 ?? '',
                container_number_26: initialFormValues?.container_info?.container_number_26 ?? '',
                container_number_27: initialFormValues?.container_info?.container_number_27 ?? '',
                container_number_28: initialFormValues?.container_info?.container_number_28 ?? '',
                container_number_29: initialFormValues?.container_info?.container_number_29 ?? '',
                container_number_30: initialFormValues?.container_info?.container_number_30 ?? '',
                container_number_31: initialFormValues?.container_info?.container_number_31 ?? '',
                container_number_32: initialFormValues?.container_info?.container_number_32 ?? '',
                container_number_33: initialFormValues?.container_info?.container_number_33 ?? '',
                container_number_34: initialFormValues?.container_info?.container_number_34 ?? '',
                container_number_35: initialFormValues?.container_info?.container_number_35 ?? '',
                container_number_36: initialFormValues?.container_info?.container_number_36 ?? '',
                container_number_37: initialFormValues?.container_info?.container_number_37 ?? '',
                container_number_38: initialFormValues?.container_info?.container_number_38 ?? '',
                container_number_39: initialFormValues?.container_info?.container_number_39 ?? '',
                container_number_40: initialFormValues?.container_info?.container_number_40 ?? '',
                container_number_41: initialFormValues?.container_info?.container_number_41 ?? '',
                container_number_42: initialFormValues?.container_info?.container_number_42 ?? '',
                container_number_43: initialFormValues?.container_info?.container_number_43 ?? '',
                container_number_44: initialFormValues?.container_info?.container_number_44 ?? '',
                container_number_45: initialFormValues?.container_info?.container_number_45 ?? '',
                container_number_46: initialFormValues?.container_info?.container_number_46 ?? '',
                container_number_47: initialFormValues?.container_info?.container_number_47 ?? '',
                container_number_48: initialFormValues?.container_info?.container_number_48 ?? '',
                container_number_49: initialFormValues?.container_info?.container_number_49 ?? '',
                container_number_50: initialFormValues?.container_info?.container_number_50 ?? '',
            },
        },
        validationSchema,
        onSubmit: (values: any) => {
            setInitialFormData({
                //1
                customs_procedure_type: values.customs_procedure_type,
                item_code_option: values.item_code_option,
                general_info: {
                    export_type_code: values.export_type_code,
                    customs_agency_code: values.customs_agency_code,
                    declaration_processing_department_code: values.declaration_processing_department_code,
                    limited_import: values.limited_import,
                    transport_mode_code: values.transport_mode_code,
                    expected_declaration_date: values.expected_declaration_date,
                    exporter_tax_code: values.exporter_tax_code,
                    exporter_name: values.exporter_name,
                    exporter_postal_code: values.exporter_postal_code,
                    exporter_address: values.exporter_address,
                    exporter_phone: values.exporter_phone,
                    export_consignor_tax_code: values.export_consignor_tax_code,
                    export_consignor_name: values.export_consignor_name,
                    importer_tax_code: values.importer_tax_code,
                    importer_name: values.importer_name,
                    importer_postal_code: values.importer_postal_code,
                    importer_address_1: values.importer_address_1,
                    importer_address_2: values.importer_address_2,
                    importer_address_3: values.importer_address_3,
                    importer_address_4: values.importer_address_4,
                    import_country_code: values.import_country_code,
                    customs_declarant_code: values.customs_declarant_code,
                    bill_of_lading_number: values.bill_of_lading_number,
                    package_quantity: values.package_quantity,
                    package_quantity_unit: values.package_quantity_unit,
                    total_gross_weight: values.total_gross_weight,
                    gross_weight_unit: values.gross_weight_unit,
                    expected_warehouse_location_code: values.expected_warehouse_location_code,
                    final_delivery_location: values.final_delivery_location,
                    final_delivery_location_name: values.final_delivery_location,
                    loading_location_code: values.loading_location_code,
                    loading_location_code_name: values.loading_location_code_name,
                    transport_vehicle_code: values.transport_vehicle_code,
                    transport_vehicle_name: values.transport_vehicle_name,
                    expected_departure_date: values.expected_departure_date,
                    package_symbol_and_number: values.package_symbol_and_number,
                    contract_number: values.contract_number,
                    contract_date: values.contract_date,
                    contract_expiration_date: values.contract_expiration_date,
                    export_license_code_1: values.export_license_code_1,
                    export_license_number_1: values.export_license_number_1,
                    export_license_code_2: values.export_license_code_2,
                    export_license_number_2: values.export_license_number_2,
                    export_license_code_3: values.export_license_code_3,
                    export_license_number_3: values.export_license_number_3,
                    export_license_code_4: values.export_license_code_4,
                    export_license_number_4: values.export_license_number_4,
                    export_license_code_5: values.export_license_code_5,
                    export_license_number_5: values.export_license_number_5,
                    invoice_type: values.invoice_type,
                    electronic_invoice_receipt_number: values.electronic_invoice_receipt_number,
                    invoice_number: values.invoice_number,
                    invoice_issue_date: values.invoice_issue_date,
                    payment_method: values.payment_method,
                    invoice_price_type: values.invoice_price_type,
                    invoice_condition: values.invoice_condition,
                    total_invoice_value: values.total_invoice_value,
                    invoice_currency_code: values.invoice_currency_code,
                    taxable_value: values.taxable_value,
                    taxable_value_currency_code: values.taxable_value_currency_code,
                    no_vnd_conversion: values.no_vnd_conversion,
                    total_tax_value_allocation_coefficient: values.total_tax_value_allocation_coefficient,
                    tax_payer: values.tax_payer,
                    tax_payment_bank_code: values.tax_payment_bank_code,
                    credit_limit_issue_year: values.credit_limit_issue_year,
                    credit_limit_document_symbol: values.credit_limit_document_symbol,
                    credit_limit_document_number: values.credit_limit_document_number,
                    tax_payment_deadline_code: values.tax_payment_deadline_code,
                    guarantee_bank_code: values.guarantee_bank_code,
                    guarantee_issue_year: values.guarantee_issue_year,
                    guarantee_document_symbol: values.guarantee_document_symbol,
                    guarantee_document_number: values.guarantee_document_number,
                    attachment_type_1: values.attachment_type_1,
                    attachment_number_1: values.attachment_number_1,
                    attachment_type_2: values.attachment_type_2,
                    attachment_number_2: values.attachment_number_2,
                    attachment_type_3: values.attachment_type_3,
                    attachment_number_3: values.attachment_number_3,
                    transport_departure_date: values.transport_departure_date,
                    transit_location_code_1: values.transit_location_code_1,
                    transit_arrival_date_1: values.transit_arrival_date_1,
                    transit_departure_date_1: values.transit_departure_date_1,
                    transit_location_code_2: values.transit_location_code_2,
                    transit_arrival_date_2: values.transit_arrival_date_2,
                    transit_departure_date_2: values.transit_departure_date_2,
                    transit_location_code_3: values.transit_location_code_3,
                    transit_arrival_date_3: values.transit_arrival_date_3,
                    transit_departure_date_3: values.transit_departure_date_3,
                    tax_transport_destination_code: values.tax_transport_destination_code,
                    tax_transport_destination_arrival_date: values.tax_transport_destination_arrival_date,
                    notes: values.notes,
                    internal_management_number: values.internal_management_number
                },
                container_info: {
                    loading_location_code_1: values.loading_location_code_1,
                    loading_location_code_2: values.loading_location_code_2,
                    loading_location_code_3: values.loading_location_code_3,
                    loading_location_code_4: values.loading_location_code_4,
                    loading_location_code_5: values.loading_location_code_5,
                    loading_location_name: values.loading_location_name,
                    address: values.address,

                    container_number_1: values.container_number_1,
                    container_number_2: values.container_number_2,
                    container_number_3: values.container_number_3,
                    container_number_4: values.container_number_4,
                    container_number_5: values.container_number_5,
                    container_number_6: values.container_number_6,
                    container_number_7: values.container_number_7,
                    container_number_8: values.container_number_8,
                    container_number_9: values.container_number_9,
                    container_number_10: values.container_number_10,
                    container_number_11: values.container_number_11,
                    container_number_12: values.container_number_12,
                    container_number_13: values.container_number_13,
                    container_number_14: values.container_number_14,
                    container_number_15: values.container_number_15,
                    container_number_16: values.container_number_16,
                    container_number_17: values.container_number_17,
                    container_number_18: values.container_number_18,
                    container_number_19: values.container_number_19,
                    container_number_20: values.container_number_20,
                    container_number_21: values.container_number_21,
                    container_number_22: values.container_number_22,
                    container_number_23: values.container_number_23,
                    container_number_24: values.container_number_24,
                    container_number_25: values.container_number_25,
                    container_number_26: values.container_number_26,
                    container_number_27: values.container_number_27,
                    container_number_28: values.container_number_28,
                    container_number_29: values.container_number_29,
                    container_number_30: values.container_number_30,
                    container_number_31: values.container_number_31,
                    container_number_32: values.container_number_32,
                    container_number_33: values.container_number_33,
                    container_number_34: values.container_number_34,
                    container_number_35: values.container_number_35,
                    container_number_36: values.container_number_36,
                    container_number_37: values.container_number_37,
                    container_number_38: values.container_number_38,
                    container_number_39: values.container_number_39,
                    container_number_40: values.container_number_40,
                    container_number_41: values.container_number_41,
                    container_number_42: values.container_number_42,
                    container_number_43: values.container_number_43,
                    container_number_44: values.container_number_44,
                    container_number_45: values.container_number_45,
                    container_number_46: values.container_number_46,
                    container_number_47: values.container_number_47,
                    container_number_48: values.container_number_48,
                    container_number_49: values.container_number_49,
                    container_number_50: values.container_number_50
                },
            });
        }
    }
}