import { ImportDefaultResponse, ImportProduct } from "types/pages/form-field";

export const mockFormImportDefault: ImportDefaultResponse = {
    "item_code_option": false,
    "general_info": {
        "import_type_code": "",
        "customs_agency_code": "",
        "individual_organization_type": "",
        "expected_declaration_date": "",
        "declaration_processing_department_code": "",
        "transport_mode_code": "",
        "importer_tax_code": "",
        "importer_name": "",
        "importer_postal_code": "",
        "importer_address": "",
        "importer_phone": "",
        "import_consignor_tax_code": "",
        "import_consignor_name": "",
        "exporter_tax_code": "",
        "exporter_name": "",
        "exporter_postal_code": "",
        "exporter_address_1": "",
        "exporter_address_2": "",
        "exporter_address_3": "",
        "exporter_address_4": "",
        "export_country_code": "",
        "export_consignor_code": "",
        "customs_declarant_code": "",
        "automated_sea_port_customs_supervision_identifier": false,
        "automated_air_port_customs_supervision_identifier": false,
        "bill_of_lading_number_1": "",
        "bill_of_lading_date_1": "",
        "mawb_number_1": "",
        "mawb_year_1": "",
        "bill_of_lading_number_2": "",
        "bill_of_lading_date_2": "",
        "mawb_number_2": "",
        "mawb_year_2": "",
        "bill_of_lading_number_3": "",
        "bill_of_lading_date_3": "",
        "mawb_number_3": "",
        "mawb_year_3": "",
        "bill_of_lading_number_4": "",
        "bill_of_lading_date_4": "",
        "mawb_number_4": "",
        "mawb_year_4": "",
        "bill_of_lading_number_5": "",
        "bill_of_lading_date_5": "",
        "mawb_number_5": "",
        "mawb_year_5": "",
        "package_quantity": null,
        "package_quantity_unit": "",
        "total_gross_weight": null,
        "gross_weight_unit": "",
        "expected_warehouse_location_code": "",
        "package_symbol_and_number": "",
        "transport_vehicle_code": "",
        "transport_vehicle_name": "",
        "arrival_date": "",
        "unloading_location_code": "",
        "loading_location_code": "",
        "container_quantity": null,
        "content_inspection_result_code": ""
    },
    "general_info_2": {
        "contract_number": "",
        "contract_date": "",
        "contract_expiration_date": "",
        "other_legal_document_code_1": "",
        "other_legal_document_code_2": "",
        "other_legal_document_code_3": "",
        "other_legal_document_code_4": "",
        "other_legal_document_code_5": "",
        "import_license_1": "",
        "import_license_2": "",
        "import_license_3": "",
        "import_license_4": "",
        "import_license_5": "",
        "invoice_type": "",
        "electronic_invoice_receipt_number": "",
        "invoice_number": "",
        "invoice_issue_date": "",
        "payment_method": "",
        "invoice_price_type": "",
        "invoice_price_condition": "",
        "total_invoice_value": null,
        "invoice_currency_code": "",
        "value_declaration_type_code": "",
        "comprehensive_value_declaration_receipt_number": "",
        "currency_code": "",
        "base_price_for_adjustment": null,
        "transport_fee_type_code": "",
        "transport_fee_currency_code": "",
        "transport_fee": null,
        "insurance_fee_type_code": "",
        "insurance_fee_currency_code": "",
        "insurance_fee": null,
        "insurance_registration_number": "",
        "adjustment_item_code_1": "",
        "adjustment_item_type_code_1": "",
        "adjustment_item_currency_code_1": "",
        "adjustment_item_value_1": null,
        "total_allocation_coefficient_1": null,
        "adjustment_item_code_2": "",
        "adjustment_item_type_code_2": "",
        "adjustment_item_currency_code_2": "",
        "adjustment_item_value_2": null,
        "total_allocation_coefficient_2": null,
        "adjustment_item_code_3": "",
        "adjustment_item_type_code_3": "",
        "adjustment_item_currency_code_3": "",
        "adjustment_item_value_3": null,
        "total_allocation_coefficient_3": null,
        "adjustment_item_code_4": "",
        "adjustment_item_type_code_4": "",
        "adjustment_item_currency_code_4": "",
        "adjustment_item_value_4": null,
        "total_allocation_coefficient_4": null,
        "adjustment_item_code_5": "",
        "adjustment_item_type_code_5": "",
        "adjustment_item_currency_code_5": "",
        "adjustment_item_value_5": null,
        "total_allocation_coefficient_5": null,
        "value_declaration_details": "",
        "total_value_allocation_coefficient": null,
        "tax_payer": "",
        "reason_code_for_bp_request": "",
        "credit_limit_issue_year": "",
        "credit_limit_document_symbol": "",
        "credit_limit_document_number": "",
        "tax_payment_deadline_code": "",
        "guarantee_bank_code": "",
        "guarantee_issue_year": "",
        "guarantee_document_symbol": "",
        "guarantee_document_number": "",
        "attachment_type_1": "",
        "attachment_number_1": "",
        "attachment_type_2": "",
        "attachment_number_2": "",
        "attachment_type_3": "",
        "attachment_number_3": "",
        "first_warehouse_entry_date": "",
        "transport_departure_date": "",
        "transit_location_1": "",
        "transit_arrival_date_1": "",
        "transit_departure_date_1": "",
        "transit_location_2": "",
        "transit_arrival_date_2": "",
        "transit_departure_date_2": "",
        "transit_location_3": "",
        "transit_arrival_date_3": "",
        "transit_departure_date_3": "",
        "tax_transport_destination": "",
        "tax_transport_destination_arrival_date": "",
        "notes_general_information_2": "",
        "internal_management_number_general_information_2": ""
    },
}

export const mockFormProductImport: ImportProduct = {
    item_code: "",
    item_name: "",
    hs_code: "",
    country_of_origin_code: "",
    quantity: null,
    quantity_unit: "",
    secondary_quantity: null,
    secondary_quantity_unit: "",
    invoice_unit_price: null,
    unit_price_currency_code: "",
    invoice_unit_price_unit: "",
    invoice_value: null,
    taxable_value: null,
    taxable_value_currency_code: "",
    import_tariff_code: "",
    import_tax_rate: null,
    import_tax_amount: null,
    special_consumption_tax_code_1: "",
    special_consumption_tax_exemption_reduction_code_1: "",
    special_consumption_tax_reduction_amount_1: null,
    environmental_tax_code_2: "",
    environmental_tax_exemption_reduction_code_2: "",
    environmental_tax_reduction_amount_2: null,
    vat_tax_code_3: "",
    vat_tax_exemption_reduction_code_3: "",
    vat_tax_reduction_amount_3: null,
    tax_rate_code_4: "",
    tax_exemption_reduction_code_4: "",
    tax_reduction_amount_4: null,
    tax_rate_code_5: "",
    tax_exemption_reduction_code_5: "",
    tax_reduction_amount_5: null,
    absolute_tax_rate: null,
    absolute_tax_rate_unit: "",
    absolute_tax_currency_code: "",
    absolute_tax_application_code: "",
    non_quota_code: "",
    adjustment_item_sequence_1: "",
    adjustment_item_sequence_2: "",
    adjustment_item_sequence_3: "",
    adjustment_item_sequence_4: "",
    adjustment_item_sequence_5: "",
    item_sequence_on_temporary_import_export_declaration: "",
    import_tax_exemption_list_registration_number: "",
    corresponding_line_in_exemption_list: "",
    import_tax_exemption_reduction_code: "",
    import_tax_reduction_amount: null,
    private_management_code: "",
}

export function initialImportFormFactory(initialFormValues: ImportDefaultResponse |
    undefined, validationSchema: any, setInitialFormData: any) {
    return {
        initialValues: {
            item_code_option: initialFormValues?.item_code_option ?? false,
            general_info: {
                import_type_code: initialFormValues?.general_info?.import_type_code ?? '',
                customs_agency_code: initialFormValues?.general_info?.customs_agency_code ?? '',
                individual_organization_type: initialFormValues?.general_info?.individual_organization_type ?? '',
                expected_declaration_date: initialFormValues?.general_info?.expected_declaration_date ?? '',
                declaration_processing_department_code: initialFormValues?.general_info?.declaration_processing_department_code ?? '',
                transport_mode_code: initialFormValues?.general_info?.transport_mode_code ?? '',
                importer_tax_code: initialFormValues?.general_info?.importer_tax_code ?? '',
                importer_name: initialFormValues?.general_info?.importer_name ?? '',
                importer_postal_code: initialFormValues?.general_info?.importer_postal_code ?? '',
                importer_address: initialFormValues?.general_info?.importer_address ?? '',
                importer_phone: initialFormValues?.general_info?.importer_phone ?? '',
                import_consignor_tax_code: initialFormValues?.general_info?.import_consignor_tax_code ?? '',
                import_consignor_name: initialFormValues?.general_info?.import_consignor_name ?? '',
                exporter_tax_code: initialFormValues?.general_info?.exporter_tax_code ?? '',
                exporter_name: initialFormValues?.general_info?.exporter_name ?? '',
                exporter_postal_code: initialFormValues?.general_info?.exporter_postal_code ?? '',
                exporter_address_1: initialFormValues?.general_info?.exporter_address_1 ?? '',
                exporter_address_2: initialFormValues?.general_info?.exporter_address_2 ?? '',
                exporter_address_3: initialFormValues?.general_info?.exporter_address_3 ?? '',
                exporter_address_4: initialFormValues?.general_info?.exporter_address_4 ?? '',
                export_country_code: initialFormValues?.general_info?.export_country_code ?? '',
                export_consignor_code: initialFormValues?.general_info?.export_consignor_code ?? '',
                customs_declarant_code: initialFormValues?.general_info?.customs_declarant_code ?? '',
                automated_sea_port_customs_supervision_identifier: initialFormValues?.general_info?.automated_sea_port_customs_supervision_identifier ?? false,
                automated_air_port_customs_supervision_identifier: initialFormValues?.general_info?.automated_air_port_customs_supervision_identifier ?? false,
                bill_of_lading_number_1: initialFormValues?.general_info?.bill_of_lading_number_1 ?? '',
                bill_of_lading_date_1: initialFormValues?.general_info?.bill_of_lading_date_1 ?? '',
                mawb_number_1: initialFormValues?.general_info?.mawb_number_1 ?? '',
                mawb_year_1: initialFormValues?.general_info?.mawb_year_1 ?? '',
                bill_of_lading_number_2: initialFormValues?.general_info?.bill_of_lading_number_2 ?? '',
                bill_of_lading_date_2: initialFormValues?.general_info?.bill_of_lading_date_2 ?? '',
                mawb_number_2: initialFormValues?.general_info?.mawb_number_2 ?? '',
                mawb_year_2: initialFormValues?.general_info?.mawb_year_2 ?? '',
                bill_of_lading_number_3: initialFormValues?.general_info?.bill_of_lading_number_3 ?? '',
                bill_of_lading_date_3: initialFormValues?.general_info?.bill_of_lading_date_3 ?? '',
                mawb_number_3: initialFormValues?.general_info?.mawb_number_3 ?? '',
                mawb_year_3: initialFormValues?.general_info?.mawb_year_3 ?? '',
                bill_of_lading_number_4: initialFormValues?.general_info?.bill_of_lading_number_4 ?? '',
                bill_of_lading_date_4: initialFormValues?.general_info?.bill_of_lading_date_4 ?? '',
                mawb_number_4: initialFormValues?.general_info?.mawb_number_4 ?? '',
                mawb_year_4: initialFormValues?.general_info?.mawb_year_4 ?? '',
                bill_of_lading_number_5: initialFormValues?.general_info?.bill_of_lading_number_5 ?? '',
                bill_of_lading_date_5: initialFormValues?.general_info?.bill_of_lading_date_5 ?? '',
                mawb_number_5: initialFormValues?.general_info?.mawb_number_5 ?? '',
                mawb_year_5: initialFormValues?.general_info?.mawb_year_5 ?? '',
                package_quantity: initialFormValues?.general_info?.package_quantity ?? null,
                package_quantity_unit: initialFormValues?.general_info?.package_quantity_unit ?? '',
                total_gross_weight: initialFormValues?.general_info?.total_gross_weight ?? null,
                gross_weight_unit: initialFormValues?.general_info?.gross_weight_unit ?? '',
                expected_warehouse_location_code: initialFormValues?.general_info?.expected_warehouse_location_code ?? '',
                package_symbol_and_number: initialFormValues?.general_info?.package_symbol_and_number ?? '',
                transport_vehicle_code: initialFormValues?.general_info?.transport_vehicle_code ?? '',
                transport_vehicle_name: initialFormValues?.general_info?.transport_vehicle_name ?? '',
                arrival_date: initialFormValues?.general_info?.arrival_date ?? '',
                unloading_location_code: initialFormValues?.general_info?.unloading_location_code ?? '',
                loading_location_code: initialFormValues?.general_info?.loading_location_code ?? '',
                container_quantity: initialFormValues?.general_info?.container_quantity ?? null,
                content_inspection_result_code: initialFormValues?.general_info?.content_inspection_result_code ?? '',
            },
            general_info_2: {
                //2.1
                contract_number: initialFormValues?.general_info_2?.contract_number ?? '',
                contract_date: initialFormValues?.general_info_2?.contract_date ?? '',
                contract_expiration_date: initialFormValues?.general_info_2?.contract_expiration_date ?? '',
                other_legal_document_code_1: initialFormValues?.general_info_2?.other_legal_document_code_1 ?? '',
                other_legal_document_code_2: initialFormValues?.general_info_2?.other_legal_document_code_2 ?? '',
                other_legal_document_code_3: initialFormValues?.general_info_2?.other_legal_document_code_3 ?? '',
                other_legal_document_code_4: initialFormValues?.general_info_2?.other_legal_document_code_4 ?? '',
                other_legal_document_code_5: initialFormValues?.general_info_2?.other_legal_document_code_5 ?? '',
                import_license_1: initialFormValues?.general_info_2?.import_license_1 ?? '',
                import_license_2: initialFormValues?.general_info_2?.import_license_2 ?? '',
                import_license_3: initialFormValues?.general_info_2?.import_license_3 ?? '',
                import_license_4: initialFormValues?.general_info_2?.import_license_4 ?? '',
                import_license_5: initialFormValues?.general_info_2?.import_license_5 ?? '',
                invoice_type: initialFormValues?.general_info_2?.invoice_type ?? '',
                electronic_invoice_receipt_number: initialFormValues?.general_info_2?.electronic_invoice_receipt_number ?? '',
                invoice_number: initialFormValues?.general_info_2?.invoice_number ?? '',
                invoice_issue_date: initialFormValues?.general_info_2?.invoice_issue_date ?? '',
                payment_method: initialFormValues?.general_info_2?.payment_method ?? '',
                invoice_price_type: initialFormValues?.general_info_2?.invoice_price_type ?? '',
                invoice_price_condition: initialFormValues?.general_info_2?.invoice_price_condition ?? '',
                total_invoice_value: initialFormValues?.general_info_2?.total_invoice_value ?? null,
                invoice_currency_code: initialFormValues?.general_info_2?.invoice_currency_code ?? '',
                value_declaration_type_code: initialFormValues?.general_info_2?.value_declaration_type_code ?? '',
                comprehensive_value_declaration_receipt_number: initialFormValues?.general_info_2?.comprehensive_value_declaration_receipt_number ?? '',
                currency_code: initialFormValues?.general_info_2?.currency_code ?? '',
                base_price_for_adjustment: initialFormValues?.general_info_2?.base_price_for_adjustment ?? null,
                transport_fee_type_code: initialFormValues?.general_info_2?.transport_fee_type_code ?? '',
                transport_fee_currency_code: initialFormValues?.general_info_2?.transport_fee_currency_code ?? '',
                transport_fee: initialFormValues?.general_info_2?.transport_fee ?? null,
                insurance_fee_type_code: initialFormValues?.general_info_2?.insurance_fee_type_code ?? '',
                insurance_fee_currency_code: initialFormValues?.general_info_2?.insurance_fee_currency_code ?? '',
                insurance_fee: initialFormValues?.general_info_2?.insurance_fee ?? null,
                insurance_registration_number: initialFormValues?.general_info_2?.insurance_registration_number ?? '',
                adjustment_item_code_1: initialFormValues?.general_info_2?.adjustment_item_code_1 ?? '',
                adjustment_item_type_code_1: initialFormValues?.general_info_2?.adjustment_item_type_code_1 ?? '',
                adjustment_item_currency_code_1: initialFormValues?.general_info_2?.adjustment_item_currency_code_1 ?? '',
                adjustment_item_value_1: initialFormValues?.general_info_2?.adjustment_item_value_1 ?? null,
                total_allocation_coefficient_1: initialFormValues?.general_info_2?.total_allocation_coefficient_1 ?? null,
                adjustment_item_code_2: initialFormValues?.general_info_2?.adjustment_item_code_2 ?? '',
                adjustment_item_type_code_2: initialFormValues?.general_info_2?.adjustment_item_type_code_2 ?? '',
                adjustment_item_currency_code_2: initialFormValues?.general_info_2?.adjustment_item_currency_code_2 ?? '',
                adjustment_item_value_2: initialFormValues?.general_info_2?.adjustment_item_value_2 ?? null,
                total_allocation_coefficient_2: initialFormValues?.general_info_2?.total_allocation_coefficient_2 ?? null,
                adjustment_item_code_3: initialFormValues?.general_info_2?.adjustment_item_code_3 ?? '',
                adjustment_item_type_code_3: initialFormValues?.general_info_2?.adjustment_item_type_code_3 ?? '',
                adjustment_item_currency_code_3: initialFormValues?.general_info_2?.adjustment_item_currency_code_3 ?? '',
                adjustment_item_value_3: initialFormValues?.general_info_2?.adjustment_item_value_3 ?? null,
                total_allocation_coefficient_3: initialFormValues?.general_info_2?.total_allocation_coefficient_3 ?? null,
                adjustment_item_code_4: initialFormValues?.general_info_2?.adjustment_item_code_4 ?? '',
                adjustment_item_type_code_4: initialFormValues?.general_info_2?.adjustment_item_type_code_4 ?? '',
                adjustment_item_currency_code_4: initialFormValues?.general_info_2?.adjustment_item_currency_code_4 ?? "",
                adjustment_item_value_4: initialFormValues?.general_info_2?.adjustment_item_value_4 ?? null,
                total_allocation_coefficient_4: initialFormValues?.general_info_2?.total_allocation_coefficient_4 ?? null,
                adjustment_item_code_5: initialFormValues?.general_info_2?.adjustment_item_code_5 ?? '',
                adjustment_item_type_code_5: initialFormValues?.general_info_2?.adjustment_item_type_code_5 ?? '',
                adjustment_item_currency_code_5: initialFormValues?.general_info_2?.adjustment_item_currency_code_5 ?? '',
                adjustment_item_value_5: initialFormValues?.general_info_2?.adjustment_item_value_5 ?? null,
                total_allocation_coefficient_5: initialFormValues?.general_info_2?.total_allocation_coefficient_5 ?? null,
                value_declaration_details: initialFormValues?.general_info_2?.value_declaration_details ?? '',
                total_value_allocation_coefficient: initialFormValues?.general_info_2?.total_value_allocation_coefficient ?? null,
                tax_payer: initialFormValues?.general_info_2?.tax_payer ?? '',
                //2.2
                reason_code_for_bp_request: initialFormValues?.general_info_2?.reason_code_for_bp_request ?? '',
                credit_limit_issue_year: initialFormValues?.general_info_2?.credit_limit_issue_year ?? '',
                credit_limit_document_symbol: initialFormValues?.general_info_2?.credit_limit_document_symbol ?? '',
                credit_limit_document_number: initialFormValues?.general_info_2?.credit_limit_document_number ?? '',
                tax_payment_deadline_code: initialFormValues?.general_info_2?.tax_payment_deadline_code ?? '',
                guarantee_bank_code: initialFormValues?.general_info_2?.guarantee_bank_code ?? '',
                guarantee_issue_year: initialFormValues?.general_info_2?.guarantee_issue_year ?? '',
                guarantee_document_symbol: initialFormValues?.general_info_2?.guarantee_document_symbol ?? '',
                guarantee_document_number: initialFormValues?.general_info_2?.guarantee_document_number ?? '',
                attachment_type_1: initialFormValues?.general_info_2?.attachment_type_1 ?? '',
                attachment_number_1: initialFormValues?.general_info_2?.attachment_number_1 ?? '',
                attachment_type_2: initialFormValues?.general_info_2?.attachment_type_2 ?? '',
                attachment_number_2: initialFormValues?.general_info_2?.attachment_number_2 ?? '',
                attachment_type_3: initialFormValues?.general_info_2?.attachment_type_3 ?? '',
                attachment_number_3: initialFormValues?.general_info_2?.attachment_number_3 ?? '',
                first_warehouse_entry_date: initialFormValues?.general_info_2?.first_warehouse_entry_date ?? '',
                transport_departure_date: initialFormValues?.general_info_2?.transport_departure_date ?? '',
                transit_location_1: initialFormValues?.general_info_2?.transit_location_1 ?? '',
                transit_arrival_date_1: initialFormValues?.general_info_2?.transit_arrival_date_1 ?? '',
                transit_departure_date_1: initialFormValues?.general_info_2?.transit_departure_date_1 ?? '',
                transit_location_2: initialFormValues?.general_info_2?.transit_location_2 ?? '',
                transit_arrival_date_2: initialFormValues?.general_info_2?.transit_arrival_date_2 ?? '',
                transit_departure_date_2: initialFormValues?.general_info_2?.transit_departure_date_2 ?? '',
                transit_location_3: initialFormValues?.general_info_2?.transit_location_3 ?? '',
                transit_arrival_date_3: initialFormValues?.general_info_2?.transit_arrival_date_3 ?? '',
                transit_departure_date_3: initialFormValues?.general_info_2?.transit_departure_date_3 ?? '',
                tax_transport_destination: initialFormValues?.general_info_2?.tax_transport_destination ?? '',
                tax_transport_destination_arrival_date: initialFormValues?.general_info_2?.tax_transport_destination_arrival_date ?? '',
                notes_general_information_2: initialFormValues?.general_info_2?.notes_general_information_2 ?? '',
                internal_management_number_general_information_2: initialFormValues?.general_info_2?.internal_management_number_general_information_2 ?? '',
            },
        },
        validationSchema,
        onSubmit: (values: any) => {
            setInitialFormData({
                //1
                customs_procedure_type: values.customs_procedure_type,
                item_code_option: values.item_code_option,
                general_info: {
                    import_type_code: values.import_type_code,
                    customs_agency_code: values.customs_agency_code,
                    individual_organization_type: values.individual_organization_type,
                    expected_declaration_date: values.expected_declaration_date,
                    declaration_processing_department_code: values.declaration_processing_department_code,
                    transport_mode_code: values.transport_mode_code,
                    importer_tax_code: values.importer_tax_code,
                    importer_name: values.importer_name,
                    importer_postal_code: values.importer_postal_code,
                    importer_address: values.importer_address,
                    importer_phone: values.importer_phone,
                    import_consignor_tax_code: values.import_consignor_tax_code,
                    import_consignor_name: values.import_consignor_name,
                    exporter_tax_code: values.exporter_tax_code,
                    exporter_name: values.exporter_name,
                    exporter_postal_code: values.exporter_postal_code,
                    exporter_address_1: values.exporter_address_1,
                    exporter_address_2: values.exporter_address_2,
                    exporter_address_3: values.exporter_address_3,
                    exporter_address_4: values.exporter_address_4,
                    export_country_code: values.export_country_code,
                    export_consignor_code: values.export_consignor_code,
                    customs_declarant_code: values.customs_declarant_code,
                    automated_sea_port_customs_supervision_identifier: values.automated_sea_port_customs_supervision_identifier,
                    automated_air_port_customs_supervision_identifier: values.automated_air_port_customs_supervision_identifier,
                    bill_of_lading_number_1: values.bill_of_lading_number_1,
                    bill_of_lading_date_1: values.bill_of_lading_date_1,
                    mawb_number_1: values.mawb_number_1,
                    mawb_year_1: values.mawb_year_1,
                    bill_of_lading_number_2: values.bill_of_lading_number_2,
                    bill_of_lading_date_2: values.bill_of_lading_date_2,
                    mawb_number_2: values.mawb_number_2,
                    mawb_year_2: values.mawb_year_2,
                    bill_of_lading_number_3: values.bill_of_lading_number_3,
                    bill_of_lading_date_3: values.bill_of_lading_date_3,
                    mawb_number_3: values.mawb_number_3,
                    mawb_year_3: values.mawb_year_3,
                    bill_of_lading_number_4: values.bill_of_lading_number_4,
                    bill_of_lading_date_4: values.bill_of_lading_date_4,
                    mawb_number_4: values.mawb_number_4,
                    mawb_year_4: values.mawb_year_4,
                    bill_of_lading_number_5: values.bill_of_lading_number_5,
                    bill_of_lading_date_5: values.bill_of_lading_date_5,
                    mawb_number_5: values.mawb_number_5,
                    mawb_year_5: values.mawb_year_5,
                    package_quantity: values.package_quantity,
                    package_quantity_unit: values.package_quantity_unit,
                    total_gross_weight: values.total_gross_weight,
                    gross_weight_unit: values.gross_weight_unit,
                    expected_warehouse_location_code: values.expected_warehouse_location_code,
                    package_symbol_and_number: values.package_symbol_and_number,
                    transport_vehicle_code: values.transport_vehicle_code,
                    transport_vehicle_name: values.transport_vehicle_name,
                    arrival_date: values.arrival_date,
                    unloading_location_code: values.unloading_location_code,
                    loading_location_code: values.loading_location_code,
                    container_quantity: values.container_quantity,
                    content_inspection_result_code: values.content_inspection_result_code,
                },
                general_info_2: {
                    // 2.1
                    contract_number: values.contract_number,
                    contract_date: values.contract_date,
                    contract_expiration_date: values.contract_expiration_date,
                    other_legal_document_code_1: values.other_legal_document_code_1,
                    other_legal_document_code_2: values.other_legal_document_code_2,
                    other_legal_document_code_3: values.other_legal_document_code_3,
                    other_legal_document_code_4: values.other_legal_document_code_4,
                    other_legal_document_code_5: values.other_legal_document_code_5,
                    import_license_1: values.import_license_1,
                    import_license_2: values.import_license_2,
                    import_license_3: values.import_license_3,
                    import_license_4: values.import_license_4,
                    import_license_5: values.import_license_5,
                    invoice_type: values.invoice_type,
                    electronic_invoice_receipt_number: values.electronic_invoice_receipt_number,
                    invoice_number: values.invoice_number,
                    invoice_issue_date: values.invoice_issue_date,
                    payment_method: values.payment_method,
                    invoice_price_type: values.invoice_price_type,
                    invoice_price_condition: values.invoice_price_condition,
                    total_invoice_value: values.total_invoice_value,
                    invoice_currency_code: values.invoice_currency_code,
                    value_declaration_type_code: values.value_declaration_type_code,
                    comprehensive_value_declaration_receipt_number: values.comprehensive_value_declaration_receipt_number,
                    currency_code: values.currency_code,
                    base_price_for_adjustment: values.base_price_for_adjustment,
                    transport_fee_type_code: values.transport_fee_type_code,
                    transport_fee_currency_code: values.transport_fee_currency_code,
                    transport_fee: values.transport_fee,
                    insurance_fee_type_code: values.insurance_fee_type_code,
                    insurance_fee_currency_code: values.insurance_fee_currency_code,
                    insurance_fee: values.insurance_fee,
                    insurance_registration_number: values.insurance_registration_number,
                    adjustment_item_code_1: values.adjustment_item_code_1,
                    adjustment_item_type_code_1: values.adjustment_item_type_code_1,
                    adjustment_item_currency_code_1: values.adjustment_item_currency_code_1,
                    adjustment_item_value_1: values.adjustment_item_value_1,
                    total_allocation_coefficient_1: values.total_allocation_coefficient_1,
                    adjustment_item_code_2: values.adjustment_item_code_2,
                    adjustment_item_type_code_2: values.adjustment_item_type_code_2,
                    adjustment_item_currency_code_2: values.adjustment_item_currency_code_2,
                    adjustment_item_value_2: values.adjustment_item_value_2,
                    total_allocation_coefficient_2: values.total_allocation_coefficient_2,
                    adjustment_item_code_3: values.adjustment_item_code_3,
                    adjustment_item_type_code_3: values.adjustment_item_type_code_3,
                    adjustment_item_currency_code_3: values.adjustment_item_currency_code_3,
                    adjustment_item_value_3: values.adjustment_item_value_3,
                    total_allocation_coefficient_3: values.total_allocation_coefficient_3,
                    adjustment_item_code_4: values.adjustment_item_code_4,
                    adjustment_item_type_code_4: values.adjustment_item_type_code_4,
                    adjustment_item_currency_code_4: values.adjustment_item_currency_code_4,
                    adjustment_item_value_4: values.adjustment_item_value_4,
                    total_allocation_coefficient_4: values.total_allocation_coefficient_4,
                    adjustment_item_code_5: values.adjustment_item_code_5,
                    adjustment_item_type_code_5: values.adjustment_item_type_code_5,
                    adjustment_item_currency_code_5: values.adjustment_item_currency_code_5,
                    adjustment_item_value_5: values.adjustment_item_value_5,
                    total_allocation_coefficient_5: values.total_allocation_coefficient_5,
                    value_declaration_details: values.value_declaration_details,
                    total_value_allocation_coefficient: values.total_value_allocation_coefficient,
                    tax_payer: values.tax_payer,
                    // 2.2
                    reason_code_for_bp_request: values.reason_code_for_bp_request,
                    credit_limit_issue_year: values.credit_limit_issue_year,
                    credit_limit_document_symbol: values.credit_limit_document_symbol,
                    credit_limit_document_number: values.credit_limit_document_number,
                    tax_payment_deadline_code: values.tax_payment_deadline_code,
                    guarantee_bank_code: values.guarantee_bank_code,
                    guarantee_issue_year: values.guarantee_issue_year,
                    guarantee_document_symbol: values.guarantee_document_symbol,
                    guarantee_document_number: values.guarantee_document_number,
                    attachment_type_1: values.attachment_type_1,
                    attachment_number_1: values.attachment_number_1,
                    attachment_type_2: values.attachment_type_2,
                    attachment_number_2: values.attachment_number_2,
                    attachment_type_3: values.attachment_type_3,
                    attachment_number_3: values.attachment_number_3,
                    first_warehouse_entry_date: values.first_warehouse_entry_date,
                    transport_departure_date: values.transport_departure_date,
                    transit_location_1: values.transit_location_1,
                    transit_arrival_date_1: values.transit_arrival_date_1,
                    transit_departure_date_1: values.transit_departure_date_1,
                    transit_location_2: values.transit_location_2,
                    transit_arrival_date_2: values.transit_arrival_date_2,
                    transit_departure_date_2: values.transit_departure_date_2,
                    transit_location_3: values.transit_location_3,
                    transit_arrival_date_3: values.transit_arrival_date_3,
                    transit_departure_date_3: values.transit_departure_date_3,
                    tax_transport_destination: values.tax_transport_destination,
                    tax_transport_destination_arrival_date: values.tax_transport_destination_arrival_date,
                    notes_general_information_2: values.notes_general_information_2,
                    internal_management_number_general_information_2: values.internal_management_number_general_information_2,
                },
            });
        }
    }
}
