// Mock data for contracts
import { sub } from 'date-fns';

// Define the Contract type based on the fields in the form
export interface Contract {
  id: number;
  contract_id: string;
  contractNumber: string;
  taxCode: string;
  sellerName: string;
  sellerAddress: string;
  contractDate: string;
  paymentTerms: string;
  deliveryTerms: string;
  contractDetails: string;
  allowableError: string;
  deliveryPort: string;
  receiptPort: string;
  currency: string;
  price: string;
  unit: string;
  totalVolume: string;
  status: 'Active' | 'Completed' | 'Pending';
  avatar?: number;
  email: string;
  // Bank information - simplified
  sellerBankName: string;
  sellerBankAccount: string;
  sellerSwiftCode: string;
  buyerBankName: string;
  buyerBankAccount: string;
  buyerSwiftCode: string;
  // LC information
  lcNumber: string;
  lcDate: string;
}

// Generate a list of mock contracts
export const mockContracts: Contract[] = [
  {
    id: 1,
    contract_id: 'CON-001',
    contractNumber: 'SL-2024-001',
    taxCode: '0123456789',
    sellerName: 'Vietnam Trading Company Ltd',
    sellerAddress: '123 Le Loi Street, District 1, Ho Chi Minh City, Vietnam',
    contractDate: sub(new Date(), { days: 15 }).toISOString().split('T')[0],
    paymentTerms: 'LC at sight',
    deliveryTerms: 'CIF',
    contractDetails: '<p>This contract is for the sale of goods as specified below. All terms and conditions are binding.</p>',
    allowableError: '±2%',
    deliveryPort: 'Ho Chi Minh City Port',
    receiptPort: 'Rotterdam Port',
    currency: 'USD',
    price: '1200',
    unit: 'Ton',
    totalVolume: '500',
    status: 'Active',
    avatar: 1,
    email: 'info@vntradingco.com',
    sellerBankName: 'VietcomBank',
    sellerBankAccount: 'VCB0001234567890',
    sellerSwiftCode: 'BFTVVNVX',
    buyerBankName: 'Deutsche Bank',
    buyerBankAccount: 'DE89370400440532013000',
    buyerSwiftCode: 'DEUTDEFF',
    lcNumber: 'LC-20240101-001',
    lcDate: sub(new Date(), { days: 10 }).toISOString().split('T')[0]
  },
  {
    id: 2,
    contract_id: 'CON-002',
    contractNumber: 'SL-2024-002',
    taxCode: '9876543210',
    sellerName: 'Hanoi Export Solutions',
    sellerAddress: '45 Pham Van Dong, Bac Tu Liem, Hanoi, Vietnam',
    contractDate: sub(new Date(), { days: 5 }).toISOString().split('T')[0],
    paymentTerms: 'T/T 30 days',
    deliveryTerms: 'FOB',
    contractDetails: '<p>Agreement for the export of agricultural products.</p>',
    allowableError: '±3%',
    deliveryPort: 'Hai Phong Port',
    receiptPort: 'Singapore Port',
    currency: 'USD',
    price: '850',
    unit: 'Ton',
    totalVolume: '300',
    status: 'Pending',
    avatar: 2,
    email: 'operations@hanoiexport.com',
    sellerBankName: 'BIDV Bank',
    sellerBankAccount: 'BIDV000987654321',
    sellerSwiftCode: 'BIDVVNVX',
    buyerBankName: 'DBS Bank',
    buyerBankAccount: 'SG8812345678901',
    buyerSwiftCode: 'DBSSSGSG',
    lcNumber: 'LC-20240115-002',
    lcDate: sub(new Date(), { days: 3 }).toISOString().split('T')[0]
  },
  {
    id: 3,
    contract_id: 'CON-003',
    contractNumber: 'SL-2024-003',
    taxCode: '5678901234',
    sellerName: 'Da Nang Industrial Products Co.',
    sellerAddress: '78 Nguyen Tat Thanh, Hai Chau, Da Nang, Vietnam',
    contractDate: sub(new Date(), { days: 30 }).toISOString().split('T')[0],
    paymentTerms: 'LC 60 days',
    deliveryTerms: 'DAP',
    contractDetails: '<p>Contract for industrial machinery export with technical support included.</p>',
    allowableError: '±1%',
    deliveryPort: 'Da Nang Port',
    receiptPort: 'Busan Port',
    currency: 'USD',
    price: '25000',
    unit: 'Set',
    totalVolume: '20',
    status: 'Completed',
    avatar: 3,
    email: 'sales@danangind.com',
    sellerBankName: 'Agribank',
    sellerBankAccount: 'AGR123456789012',
    sellerSwiftCode: 'VBAAVNVX',
    buyerBankName: 'Shinhan Bank',
    buyerBankAccount: 'KR9987654321000',
    buyerSwiftCode: 'SHBKKRSE',
    lcNumber: 'LC-20231220-003',
    lcDate: sub(new Date(), { days: 25 }).toISOString().split('T')[0]
  },
  {
    id: 4,
    contract_id: 'CON-004',
    contractNumber: 'SL-2024-004',
    taxCode: '1122334455',
    sellerName: 'Mekong Delta Food Export',
    sellerAddress: '56 Tran Hung Dao, Can Tho, Vietnam',
    contractDate: sub(new Date(), { days: 2 }).toISOString().split('T')[0],
    paymentTerms: 'CAD',
    deliveryTerms: 'CIP',
    contractDetails: '<p>Contract for premium rice exports to international markets.</p>',
    allowableError: '±2.5%',
    deliveryPort: 'Can Tho Port',
    receiptPort: 'Hong Kong Port',
    currency: 'USD',
    price: '950',
    unit: 'Ton',
    totalVolume: '800',
    status: 'Active',
    avatar: 4,
    email: 'export@mekongfood.vn',
    sellerBankName: 'Techcombank',
    sellerBankAccount: 'TCB5566778899',
    sellerSwiftCode: 'VTCBVNVX',
    buyerBankName: 'HSBC Hong Kong',
    buyerBankAccount: 'HK4466889900112',
    buyerSwiftCode: 'HSBCHKHH',
    lcNumber: 'LC-20240125-004',
    lcDate: sub(new Date(), { days: 1 }).toISOString().split('T')[0]
  },
  {
    id: 5,
    contract_id: 'CON-005',
    contractNumber: 'SL-2024-005',
    taxCode: '9988776655',
    sellerName: 'Phu Quoc Seafood Co.',
    sellerAddress: '12 Tran Phu, Duong Dong, Phu Quoc, Vietnam',
    contractDate: sub(new Date(), { days: 45 }).toISOString().split('T')[0],
    paymentTerms: 'T/T 50% advance, 50% before shipping',
    deliveryTerms: 'EXW',
    contractDetails: '<p>Agreement for premium seafood supply from Phu Quoc island.</p>',
    allowableError: '±5%',
    deliveryPort: 'Phu Quoc Port',
    receiptPort: 'Tokyo Port',
    currency: 'JPY',
    price: '12000',
    unit: 'Kg',
    totalVolume: '5000',
    status: 'Completed',
    avatar: 5,
    email: 'contact@phuquocseafood.com',
    sellerBankName: 'VPBank',
    sellerBankAccount: 'VPB112233445566',
    sellerSwiftCode: 'VPBKVNVX',
    buyerBankName: 'MUFG Bank',
    buyerBankAccount: 'JP6677889900',
    buyerSwiftCode: 'BOTKJPJT',
    lcNumber: 'LC-20231201-005',
    lcDate: sub(new Date(), { days: 40 }).toISOString().split('T')[0]
  },
  {
    id: 6,
    contract_id: 'CON-006',
    contractNumber: 'SL-2024-006',
    taxCode: '5544332211',
    sellerName: 'Saigon Tech Exports',
    sellerAddress: '78 Nguyen Hue Boulevard, District 1, Ho Chi Minh City, Vietnam',
    contractDate: sub(new Date(), { days: 8 }).toISOString().split('T')[0],
    paymentTerms: 'LC 45 days',
    deliveryTerms: 'FCA',
    contractDetails: '<p>Contract for high-tech components and consumer electronics export.</p>',
    allowableError: '±1.5%',
    deliveryPort: 'Cat Lai Port',
    receiptPort: 'Los Angeles Port',
    currency: 'USD',
    price: '5400',
    unit: 'Pallet',
    totalVolume: '50',
    status: 'Active',
    avatar: 6,
    email: 'export@saigontech.vn',
    sellerBankName: 'ACB Bank',
    sellerBankAccount: 'ACB8877665544',
    sellerSwiftCode: 'ASCBVNVX',
    buyerBankName: 'Bank of America',
    buyerBankAccount: 'US9988776655',
    buyerSwiftCode: 'BOFAUS3N',
    lcNumber: 'LC-20240118-006',
    lcDate: sub(new Date(), { days: 7 }).toISOString().split('T')[0]
  },
  {
    id: 7,
    contract_id: 'CON-007',
    contractNumber: 'SL-2024-007',
    taxCode: '1357924680',
    sellerName: 'Hue Traditional Crafts Co.',
    sellerAddress: '25 Le Loi Street, Hue City, Thua Thien Hue, Vietnam',
    contractDate: sub(new Date(), { days: 21 }).toISOString().split('T')[0],
    paymentTerms: 'T/T 100% advance',
    deliveryTerms: 'DDP',
    contractDetails: '<p>Contract for handcrafted traditional Vietnamese artwork and home decor items.</p>',
    allowableError: '±3%',
    deliveryPort: 'Chan May Port',
    receiptPort: 'Sydney Port',
    currency: 'AUD',
    price: '12500',
    unit: 'Container',
    totalVolume: '5',
    status: 'Pending',
    avatar: 7,
    email: 'sales@huecrafts.vn',
    sellerBankName: 'Sacombank',
    sellerBankAccount: 'STB2468013579',
    sellerSwiftCode: 'SGTTVNVX',
    buyerBankName: 'Commonwealth Bank',
    buyerBankAccount: 'AU5544332211',
    buyerSwiftCode: 'CTBAAU2S',
    lcNumber: 'LC-20240110-007',
    lcDate: sub(new Date(), { days: 19 }).toISOString().split('T')[0]
  },
  {
    id: 8,
    contract_id: 'CON-008',
    contractNumber: 'SL-2024-008',
    taxCode: '2468135790',
    sellerName: 'Highland Coffee Exporters',
    sellerAddress: '123 Nguyen Van Cu, Buon Ma Thuot, Dak Lak, Vietnam',
    contractDate: sub(new Date(), { days: 12 }).toISOString().split('T')[0],
    paymentTerms: 'D/P 30 days',
    deliveryTerms: 'CFR',
    contractDetails: '<p>Premium coffee beans export from Vietnam\'s Central Highlands region.</p>',
    allowableError: '±2%',
    deliveryPort: 'Quy Nhon Port',
    receiptPort: 'Hamburg Port',
    currency: 'EUR',
    price: '3800',
    unit: 'Ton',
    totalVolume: '120',
    status: 'Active',
    avatar: 8,
    email: 'orders@highlandcoffee.vn',
    sellerBankName: 'MB Bank',
    sellerBankAccount: 'MB9876543210',
    sellerSwiftCode: 'MSCBVNVX',
    buyerBankName: 'Commerzbank',
    buyerBankAccount: 'DE12345678900',
    buyerSwiftCode: 'COBADEFF',
    lcNumber: 'LC-20240115-008',
    lcDate: sub(new Date(), { days: 10 }).toISOString().split('T')[0]
  },
  {
    id: 9,
    contract_id: 'CON-009',
    contractNumber: 'SL-2024-009',
    taxCode: '9876501234',
    sellerName: 'Vinh Long Fruit Export',
    sellerAddress: '45 Hung Vuong, Vinh Long City, Vinh Long, Vietnam',
    contractDate: sub(new Date(), { days: 4 }).toISOString().split('T')[0],
    paymentTerms: 'CAD against BOL',
    deliveryTerms: 'FOB',
    contractDetails: '<p>Contract for export of fresh tropical fruits from Mekong Delta region.</p>',
    allowableError: '±4%',
    deliveryPort: 'My Tho Port',
    receiptPort: 'Dubai Port',
    currency: 'USD',
    price: '1350',
    unit: 'Ton',
    totalVolume: '75',
    status: 'Pending',
    avatar: 9,
    email: 'info@vinhlongfruit.com',
    sellerBankName: 'HDBank',
    sellerBankAccount: 'HDB1122334455',
    sellerSwiftCode: 'HDBCVNVX',
    buyerBankName: 'Emirates NBD',
    buyerBankAccount: 'AE8877665544',
    buyerSwiftCode: 'EBILAEAD',
    lcNumber: 'LC-20240122-009',
    lcDate: sub(new Date(), { days: 3 }).toISOString().split('T')[0]
  },
  {
    id: 10,
    contract_id: 'CON-010',
    contractNumber: 'SL-2024-010',
    taxCode: '7531902468',
    sellerName: 'Halong Marine Products JSC',
    sellerAddress: '78 Ha Long, Hong Gai, Quang Ninh, Vietnam',
    contractDate: sub(new Date(), { days: 35 }).toISOString().split('T')[0],
    paymentTerms: 'LC 90 days',
    deliveryTerms: 'CIF',
    contractDetails: '<p>Export contract for premium seafood and marine products from North Vietnam.</p>',
    allowableError: '±2.5%',
    deliveryPort: 'Cai Lan Port',
    receiptPort: 'Barcelona Port',
    currency: 'EUR',
    price: '9200',
    unit: 'Ton',
    totalVolume: '40',
    status: 'Completed',
    avatar: 10,
    email: 'export@halongmarine.vn',
    sellerBankName: 'LienVietPostBank',
    sellerBankAccount: 'LVPB7788990011',
    sellerSwiftCode: 'LVBKVNVX',
    buyerBankName: 'CaixaBank',
    buyerBankAccount: 'ES1122334455',
    buyerSwiftCode: 'CAIXESBB',
    lcNumber: 'LC-20231215-010',
    lcDate: sub(new Date(), { days: 33 }).toISOString().split('T')[0]
  },
  {
    id: 11,
    contract_id: 'CON-011',
    contractNumber: 'SL-2024-011',
    taxCode: '1029384756',
    sellerName: 'Binh Dinh Furniture Manufacturing',
    sellerAddress: '56 Tran Hung Dao, Quy Nhon, Binh Dinh, Vietnam',
    contractDate: sub(new Date(), { days: 18 }).toISOString().split('T')[0],
    paymentTerms: 'T/T 30% advance, 70% after inspection',
    deliveryTerms: 'FAS',
    contractDetails: '<p>Contract for high-quality wooden furniture export to North American market.</p>',
    allowableError: '±1%',
    deliveryPort: 'Quy Nhon Port',
    receiptPort: 'Vancouver Port',
    currency: 'CAD',
    price: '28500',
    unit: 'Container',
    totalVolume: '15',
    status: 'Active',
    avatar: 11,
    email: 'sales@binhdinhtimber.vn',
    sellerBankName: 'OCB Bank',
    sellerBankAccount: 'OCB5566778899',
    sellerSwiftCode: 'ORCOVNVX',
    buyerBankName: 'Royal Bank of Canada',
    buyerBankAccount: 'CA1234567890',
    buyerSwiftCode: 'ROYCCAT2',
    lcNumber: 'LC-20240112-011',
    lcDate: sub(new Date(), { days: 15 }).toISOString().split('T')[0]
  },
  {
    id: 12,
    contract_id: 'CON-012',
    contractNumber: 'SL-2024-012',
    taxCode: '3141592653',
    sellerName: 'Tay Ninh Rubber Company',
    sellerAddress: '123 Cach Mang Thang 8, Tay Ninh City, Tay Ninh, Vietnam',
    contractDate: sub(new Date(), { days: 25 }).toISOString().split('T')[0],
    paymentTerms: 'Open Account 60 days',
    deliveryTerms: 'DAT',
    contractDetails: '<p>Contract for natural rubber export to international tire manufacturers.</p>',
    allowableError: '±3%',
    deliveryPort: 'Vung Tau Port',
    receiptPort: 'Chennai Port',
    currency: 'USD',
    price: '1850',
    unit: 'Ton',
    totalVolume: '350',
    status: 'Active',
    avatar: 12,
    email: 'sales@tayninhrubber.com',
    sellerBankName: 'SHB Bank',
    sellerBankAccount: 'SHB9988776655',
    sellerSwiftCode: 'SHBAVNVX',
    buyerBankName: 'State Bank of India',
    buyerBankAccount: 'IN5544332211',
    buyerSwiftCode: 'SBININBB',
    lcNumber: 'LC-20240105-012',
    lcDate: sub(new Date(), { days: 22 }).toISOString().split('T')[0]
  },
];

// Export a function to get contract by ID
export const getContractById = (id: number): Contract | undefined => {
  return mockContracts.find(contract => contract.id === id);
}; 